server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
spring:
  application:
    name: consumer-service
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
