server:
  port: 10010
zuul:
  routes:
    product-service:
      path: /user/**
      serviceId: PRODUCT-SERVICE
      strip-prefix: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
spring:
  application:
    name: zuul-service